# frozen_string_literal: true

json.issuer Oauth::Issuer.identifier
json.authorization_endpoint oauth_authorizations_url
json.token_endpoint oauth_tokens_url
json.token_endpoint_auth_methods_supported %i[client_secret_basic client_secret_post private_key_jwt none]
json.token_endpoint_auth_signing_alg_values_supported JwtBearerAssertion::ALGORITHMS
json.userinfo_endpoint oauth_me_url
json.jwks_uri jwks_url
json.registration_endpoint oauth_clients_url
json.revocation_endpoint revoke_oauth_tokens_url
json.revocation_endpoint_auth_methods_supported %i[client_secret_basic client_secret_post private_key_jwt]
json.introspection_endpoint introspect_oauth_tokens_url
json.introspection_endpoint_auth_methods_supported %i[client_secret_basic client_secret_post private_key_jwt]
json.scopes_supported Scopes::SUPPORTED
json.response_types_supported Client::RESPONSE_TYPES
json.response_modes_supported %w[query]
json.grant_types_supported Client::GRANT_TYPES
json.code_challenge_methods_supported %w[S256]
json.authorization_response_iss_parameter_supported true
json.device_authorization_endpoint oauth_device_authorization_url
json.pushed_authorization_request_endpoint oauth_par_url
json.require_pushed_authorization_requests false
json.request_parameter_supported true
json.request_uri_parameter_supported true
json.require_signed_request_object false
json.request_object_signing_alg_values_supported RequestObject::ALGORITHMS
json.dpop_signing_alg_values_supported DpopProof::ALGORITHMS
json.service_documentation root_url + 'doc'
json.ui_locales_supported I18n.available_locales
